// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx9ZWovaV0WbljzF2ktiVrhvJ7UOD9kOI',
    appId: '1:943864544493:web:9e8928c416e3c36c7fa0e4',
    messagingSenderId: '943864544493',
    projectId: 'tech-challenge-flutter-e51db',
    authDomain: 'tech-challenge-flutter-e51db.firebaseapp.com',
    storageBucket: 'tech-challenge-flutter-e51db.firebasestorage.app',
    measurementId: 'G-H78P6JBQCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfNE_MlQ8-JiR0WZkGUeAXBeGvHarN-Bw',
    appId: '1:943864544493:android:5c72a21341cd48ff7fa0e4',
    messagingSenderId: '943864544493',
    projectId: 'tech-challenge-flutter-e51db',
    storageBucket: 'tech-challenge-flutter-e51db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW7LaY9YAfh3L6Ch2qC0IZ65ByEMsxRlE',
    appId: '1:943864544493:ios:31b1f9f50dd271e27fa0e4',
    messagingSenderId: '943864544493',
    projectId: 'tech-challenge-flutter-e51db',
    storageBucket: 'tech-challenge-flutter-e51db.firebasestorage.app',
    iosBundleId: 'com.example.techChallenge3',
  );
}
